# Generated by Django 5.2.17 on 2026-09-18 15:12

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellido_paterno'],
                'permissions': (('ver_detalle_productor', 'Puede ver detalle de Productor'), ('cargar_productores', 'Puede cargar productores desde un archivo externo'), ('ver_tabla_productores', 'Puede ver tabla de productores'), ('ver_reporte_productores_excel', 'Puede ver Reporte de productores en excel')),
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('abreviatura', models.CharField(max_length=7)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['descripcion'],
                'permissions': (('ver_detalle_profesion', 'Puede ver detalle de Profesion'), ('cargar_profesiones', 'Puede cargar profesiones desde un archivo externo'), ('ver_tabla_profesiones', 'Puede ver tabla de Profesiones'), ('ver_reporte_profesiones_excel', 'Puede ver Reporte de Profesiones en excel')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dni', models.CharField(db_index=True, max_length=8)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical productor',
                'verbose_name_plural': 'historical productors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfesion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('abreviatura', models.CharField(max_length=7)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical profesion',
                'verbose_name_plural': 'historical profesions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NivelAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.CharField(max_length=100)),
                ('nivel_superior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='administracion.nivelaprobacion')),
            ],
            options={
                'ordering': ['descripcion'],
                'permissions': (('ver_detalle_nivel_aprobacion', 'Puede ver detalle de Nivel de Aprobacion'), ('cargar_niveles_aprobacion', 'Puede cargar niveles de aprobacion desde un archivo externo'), ('ver_tabla_niveles_aprobacion', 'Puede ver tabla de Puestos'), ('ver_reporte_niveles_aprobacion_excel', 'Puede ver Reporte de niveles de aprobacion en excel')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalNivelAprobacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nivel_superior', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.nivelaprobacion')),
            ],
            options={
                'verbose_name': 'historical nivel aprobacion',
                'verbose_name_plural': 'historical nivel aprobacions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('es_gerencia', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='administracion.oficina')),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('ver_bienvenida', 'Puede ver bienvenida a la aplicación'), ('cargar_oficinas', 'Puede cargar oficinas desde un archivo externo'), ('ver_detalle_oficina', 'Puede ver detalle de Oficina'), ('ver_tabla_oficinas', 'Puede ver tabla de Oficinas'), ('ver_reporte_oficinas_excel', 'Puede ver Reporte de Oficinas en excel')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalOficina',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(db_index=True, max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('es_gerencia', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dependencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.oficina')),
            ],
            options={
                'verbose_name': 'historical oficina',
                'verbose_name_plural': 'historical oficinas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrabajador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dni', models.CharField(db_index=True, max_length=8)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('firma', models.TextField(max_length=100)),
                ('foto', models.TextField(default='trabajadores/sinimagen.png', max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profesion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.profesion')),
            ],
            options={
                'verbose_name': 'historical trabajador',
                'verbose_name_plural': 'historical trabajadors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('firma', models.ImageField(upload_to='firmas')),
                ('foto', models.ImageField(default='trabajadores/sinimagen.png', upload_to='trabajadores')),
                ('estado', models.BooleanField(default=True)),
                ('profesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.profesion')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido_paterno'],
                'permissions': (('ver_detalle_trabajador', 'Puede ver detalle de Trabajador'), ('cargar_trabajadores', 'Puede cargar trabajadores desde un archivo externo'), ('ver_tabla_trabajadores', 'Puede ver tabla de Trabajadores'), ('ver_reporte_trabajadores_excel', 'Puede ver Reporte de Trabajadores en excel')),
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('es_jefatura', models.BooleanField(default=False)),
                ('es_asistente', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.oficina')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.trabajador')),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('ver_detalle_puesto', 'Puede ver detalle de Puesto'), ('cargar_puestos', 'Puede cargar puestos desde un archivo externo'), ('ver_tabla_puestos', 'Puede ver tabla de Puestos'), ('ver_reporte_puestos_excel', 'Puede ver Reporte de Puestos en excel')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPuesto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('es_jefatura', models.BooleanField(default=False)),
                ('es_asistente', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.oficina')),
                ('trabajador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.trabajador')),
            ],
            options={
                'verbose_name': 'historical puesto',
                'verbose_name_plural': 'historical puestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
