# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:55
from __future__ import unicode_literals

import administracion.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('administracion', '0002_upload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='archivo',
            field=models.FileField(max_length=500, storage=administracion.helpers.OverwriteStorage(),
                                   upload_to=b'archivos'),
        ),
    ]
