# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20161031_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='uploaded_at',
        ),
    ]
