# Generated by Django 5.2.17 on 2026-09-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
    ]
