# Generated by Django 5.2.17 on 2026-09-21 21:38

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('account_number', models.CharField(max_length=12, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_divisional', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['account_number'],
                'permissions': (('cargar_cuentas_contables', 'Puede cargar Cuentas Contables desde un archivo externo'), ('ver_detalle_cuenta_contable', 'Puede ver detalle de Cuenta Contable'), ('ver_tabla_cuentas_contables', 'Puede ver tabla de Cuentas Contables'), ('ver_reporte_cuentas_contables_excel', 'Puede ver Reporte Cuentas Contables en excel')),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('tax_id', models.CharField(max_length=11)),
                ('logo', models.ImageField(upload_to='configuration')),
                ('place', models.CharField(default='', max_length=150)),
                ('street', models.CharField(default='', max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mail_host', models.CharField(max_length=70)),
                ('mail_port', models.IntegerField(default=25)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('uses_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sunat_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sunat_code'],
                'permissions': (('cargar_tipos_documento', 'Puede cargar Tipos de Documento desde un archivo externo'), ('ver_detalle_tipo_documento', 'Puede ver detalle Tipo de Documento'), ('ver_tabla_tipos_documentos', 'Puede ver tabla de Tipos de Documentos'), ('ver_reporte_tipos_documentos_excel', 'Puede ver Reporte de Tipos de Documentos en excel')),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['date'],
                'permissions': (('ver_detalle_tipo_cambio', 'Puede ver detalle de Tipo de Cambio'), ('ver_tabla_tipos_cambio', 'Puede ver tabla de Tipos de Cambio'), ('ver_reporte_tipos_cambio_excel', 'Puede ver Reporte Tipos de Cambio en excel')),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('credit_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('cargar_formas_pago', 'Puede cargar Formas de Pago desde un archivo externo'), ('ver_detalle_forma_pago', 'Puede ver detalle de Forma de Pago'), ('ver_tabla_formas_pago', 'Puede ver tabla Formas de Pago'), ('ver_reporte_formas_pago_excel', 'Puede ver Reporte de Formas de Pago en excel')),
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sunat_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Existencia',
                'verbose_name_plural': 'Tipos de Existencias',
                'permissions': (('ver_tabla_tipos_existencias', 'Puede ver tabla de Tipos de Existencias'),),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_type', models.CharField(choices=[('COM', 'COMPRA'), ('VEN', 'VEN')], default='COM', max_length=20)),
            ],
            options={
                'ordering': ['abbreviation'],
                'permissions': (('ver_detalle_impuesto', 'Puede ver detalle Impuesto'), ('ver_tabla_impuestos', 'Puede ver tabla de Impuestos'), ('ver_reporte_impuestos_excel', 'Puede ver Reporte de Impuestos en excel')),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('table', models.CharField(max_length=25)),
                ('field_description', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=10)),
                ('value_description', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['code'],
                'permissions': (('ver_detalle_tipo', 'Puede ver detalle Tipo de Documento'), ('ver_tabla_tipos', 'Puede ver tabla de Tipos de Documentos'), ('ver_reporte_tipos_excel', 'Puede ver Reporte de Tipos de Documentos en excel')),
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='archivos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('administration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration', to='administracion.office')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='administracion.office')),
                ('logistics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='administracion.office')),
                ('operations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='administracion.office')),
                ('purchase_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='contabilidad.tax')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
