# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 19:01
from __future__ import unicode_literals

import contabilidad.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='archivo',
            field=models.FileField(max_length=150, storage=contabilidad.helpers.OverwriteStorage(), upload_to=b'archivos'),
        ),
    ]
