# Generated by Django 5.2.17 on 2026-09-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoexistencia',
            options={'permissions': (('ver_tabla_tipos_existencias', 'Puede ver tabla de Tipos de Existencias'),), 'verbose_name': 'Tipo de Existencia', 'verbose_name_plural': 'Tipos de Existencias'},
        ),
    ]
