# Generated by Django 5.2.17 on 2026-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequirementdetail',
            name='otro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='otro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
