# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='desc_abreviada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='desc_abreviada',
        ),
    ]
