# Generated by Django 5.2.17 on 2026-09-21 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('received_date', models.DateField(null=True)),
                ('month', models.IntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('notes', models.TextField()),
                ('report', models.FileField(null=True, upload_to='informes')),
                ('direct_delivery_to_requester', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PEND', 'PENDIENTE'), ('COTIZ', 'COTIZADO'), ('COTIZ_PARC', 'COTIZADO PARCIALMENTE'), ('COMP', 'COMPRADO'), ('COMP_PARC', 'COMPRADO PARCIALMENTE'), ('ATEN', 'ATENDIDO'), ('ATEN_PARC', 'ATENDIDO PARCIALMENTE'), ('CANC', 'CANCELADO')], default='PEND', max_length=20, verbose_name='Estado')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='administracion.oficina')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='administracion.trabajador')),
            ],
            options={
                'permissions': (('ver_bienvenida', 'Puede ver bienvenida a la aplicación'), ('ver_detalle_requerimiento', 'Puede ver detalle de Requerimiento'), ('ver_tabla_requerimientos', 'Puede ver tabla de Requerimientos'), ('ver_reporte_requerimientos_excel', 'Puede ver Reporte de Requerimientos en excel'), ('puede_hacer_transferencia_requerimiento', 'Puede hacer transferencia de Requerimiento')),
            },
        ),
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('line_number', models.IntegerField()),
                ('use', models.TextField(null=True)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('quoted_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('purchased_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('served_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PEND', 'PENDIENTE'), ('COTIZ', 'COTIZADO'), ('COTIZ_PARC', 'COTIZADO PARCIALMENTE'), ('COMP', 'COMPRADO'), ('COMP_PARC', 'COMPRADO PARCIALMENTE'), ('ATEN', 'ATENDIDO'), ('ATEN_PARC', 'ATENDIDO PARCIALMENTE'), ('CANC', 'CANCELADO')], default='PEND', max_length=20)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_details', to='productos.producto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='requerimientos.requerimiento')),
            ],
            options={
                'ordering': ['line_number'],
                'permissions': (('can_view', 'Can view Detalle Requerimiento'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalAprobacionRequerimiento',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('rejection_reason', models.TextField(default='')),
                ('received_date', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.nivelaprobacion')),
                ('requerimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requerimientos.requerimiento')),
            ],
            options={
                'verbose_name': 'historical aprobacion requerimiento',
                'verbose_name_plural': 'historical aprobacion requerimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDetalleRequerimiento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('line_number', models.IntegerField()),
                ('use', models.TextField(null=True)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('quoted_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('purchased_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('served_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PEND', 'PENDIENTE'), ('COTIZ', 'COTIZADO'), ('COTIZ_PARC', 'COTIZADO PARCIALMENTE'), ('COMP', 'COMPRADO'), ('COMP_PARC', 'COMPRADO PARCIALMENTE'), ('ATEN', 'ATENDIDO'), ('ATEN_PARC', 'ATENDIDO PARCIALMENTE'), ('CANC', 'CANCELADO')], default='PEND', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.producto')),
                ('requerimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requerimientos.requerimiento')),
            ],
            options={
                'verbose_name': 'historical detalle requerimiento',
                'verbose_name_plural': 'historical detalle requerimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRequerimiento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('received_date', models.DateField(null=True)),
                ('month', models.IntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('notes', models.TextField()),
                ('report', models.TextField(max_length=100, null=True)),
                ('direct_delivery_to_requester', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PEND', 'PENDIENTE'), ('COTIZ', 'COTIZADO'), ('COTIZ_PARC', 'COTIZADO PARCIALMENTE'), ('COMP', 'COMPRADO'), ('COMP_PARC', 'COMPRADO PARCIALMENTE'), ('ATEN', 'ATENDIDO'), ('ATEN_PARC', 'ATENDIDO PARCIALMENTE'), ('CANC', 'CANCELADO')], default='PEND', max_length=20, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.oficina')),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.trabajador')),
            ],
            options={
                'verbose_name': 'historical requerimiento',
                'verbose_name_plural': 'historical requerimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AprobacionRequerimiento',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requerimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='approval', serialize=False, to='requerimientos.requerimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('rejection_reason', models.TextField(default='')),
                ('received_date', models.DateField(null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='administracion.nivelaprobacion')),
            ],
            options={
                'permissions': (('ver_tabla_aprobacion_requerimientos', 'Puede ver tabla de Aprobación de Requerimientos'), ('ver_reporte_aprobacion_requerimientos_excel', 'Puede ver Reporte de Aprobación de Requerimientos en excel')),
            },
        ),
    ]
