# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 10:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nro_detalle', models.IntegerField()),
                ('uso', models.TextField(null=True)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=15)),
                ('cantidad_cotizada', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('cantidad_comprada', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('cantidad_atendida', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[(b'PEND', b'PENDIENTE'), (b'COTIZ', b'COTIZADO'), (b'COTIZ_PARC', b'COTIZADO PARCIALMENTE'), (b'COMP', b'COMPRADO'), (b'COMP_PARC', b'COMPRADO PARCIALMENTE'), (b'ATEN', b'ATENDIDO'), (b'ATEN_PARC', b'ATENDIDO PARCIALMENTE'), (b'CANC', b'CANCELADO')], default=b'PEND', max_length=20)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
            options={
                'ordering': ['nro_detalle'],
                'permissions': (('can_view', 'Can view Detalle Requerimiento'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalAprobacionRequerimiento',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('estado', models.BooleanField(default=True)),
                ('motivo_desaprobacion', models.TextField(default=b'')),
                ('fecha_recepcion', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administracion.NivelAprobacion')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical aprobacion requerimiento',
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_recepcion', models.DateField(null=True)),
                ('mes', models.IntegerField(choices=[(1, b'ENERO'), (2, b'FEBRERO'), (3, b'MARZO'), (4, b'ABRIL'), (5, b'MAYO'), (6, b'JUNIO'), (7, b'JULIO'), (8, b'AGOSTO'), (9, b'SETIEMBRE'), (10, b'OCTUBRE'), (11, b'NOVIEMBRE'), (12, b'DICIEMBRE')])),
                ('annio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('observaciones', models.TextField()),
                ('informe', models.FileField(null=True, upload_to=b'informes')),
                ('entrega_directa_solicitante', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[(b'PEND', b'PENDIENTE'), (b'COTIZ', b'COTIZADO'), (b'COTIZ_PARC', b'COTIZADO PARCIALMENTE'), (b'COMP', b'COMPRADO'), (b'COMP_PARC', b'COMPRADO PARCIALMENTE'), (b'ATEN', b'ATENDIDO'), (b'ATEN_PARC', b'ATENDIDO PARCIALMENTE'), (b'CANC', b'CANCELADO')], default=b'PEND', max_length=20)),
            ],
            options={
                'permissions': (('ver_bienvenida', 'Puede ver bienvenida a la aplicaci\xf3n'), ('ver_detalle_requerimiento', 'Puede ver detalle de Requerimiento'), ('ver_tabla_requerimientos', 'Puede ver tabla de Requerimientos'), ('ver_reporte_requerimientos_excel', 'Puede ver Reporte de Requerimientos en excel'), ('puede_hacer_transferencia_requerimiento', 'Puede hacer transferencia de Requerimiento')),
            },
        ),
        migrations.CreateModel(
            name='AprobacionRequerimiento',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requerimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='requerimientos.Requerimiento')),
                ('estado', models.BooleanField(default=True)),
                ('motivo_desaprobacion', models.TextField(default=b'')),
                ('fecha_recepcion', models.DateField(null=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.NivelAprobacion')),
            ],
            options={
                'permissions': (('ver_tabla_aprobacion_requerimientos', 'Puede ver tabla de Aprobaci\xf3n de Requerimientos'), ('ver_reporte_aprobacion_requerimientos_excel', 'Puede ver Reporte de Aprobaci\xf3n de Requerimientos en excel')),
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Oficina'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Trabajador'),
        ),
        migrations.AddField(
            model_name='historicalaprobacionrequerimiento',
            name='requerimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requerimientos.Requerimiento'),
        ),
        migrations.AddField(
            model_name='detallerequerimiento',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.Requerimiento'),
        ),
    ]
